name: Build and Upload Artifacts
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Download dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
    # run: npm test

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kdc-overlay-front
        path: dist/
