name: Continuous Integration
on: ["push", "pull_request"]

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #####################
      # Setup Environment #
      #####################

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      #########
      # Build #
      #########

      - name: Download dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
      # run: npm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kdc-overlay-front
          path: dist/

      ######################
      # Check Version Bump #
      ######################

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

      ############################
      # Create Release if Bumped #
      ############################

      - name: Download Build Artifacts
        if: steps.check.outputs.changed == 'true'
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          skip_unpack: true

      - name: Release
        if: steps.check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.check.outputs.version }}
          tag_name: v${{ steps.check.outputs.version }}
          generate_release_notes: true
          files: kdc-overlay-front.zip
